### ISSUE TITLE
should migrate to Enum class

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/peyotl#62]
There are some "fake" enum classes in peyotl. I just found out that you can import py3 enums in py2.7 with the enum34 package.
We should migrate to using that for the sake of internal consistency.

**Comment by jimallman** [comment]
This migration to enum34 was [done some time ago](https://github.com/OpenTreeOfLife/peyotl/commit/bd3b57091d235144ea0662c6ab119f977a23f16f), and it's been problematic. Now in testing **devtree**, it seems our pinned version 1.1.8 is no longer working (doesn't expose module `enum` to python2.7):
```shell
deploy@ip-172-30-1-156:~/venv_web2py$ bin/python
Python 2.7.18 (default, Mar  8 2021, 13:02:45)
...
>>> import peyotl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deploy/repos/peyotl/peyotl/__init__.py", line 30, in <module>
    from peyotl.phylo.entities import OTULabelStyleEnum
  File "/home/deploy/repos/peyotl/peyotl/phylo/entities.py", line 2, in <module>
    from enum import Enum
ImportError: No module named enum
>>>
deploy@ip-172-30-1-156:~/venv_web2py$ bin/pip show enum34
...
Name: enum34
Version: 1.1.8
```
Upgrading `enum34` to 1.1.9 or 1.1.10 allows importing peyotl, but might cause [another bug that led to us pinning it](https://github.com/OpenTreeOfLife/peyotl/blob/01a4f280a96d44b9d8cdfc5f11b94f2b32fcf61b/setup.py) to 1.1.8.

According to the original `enum34` author, [their newer aenum is now recommended instead](https://github.com/ethanfurman/enum34/issues/1#issuecomment-900492321). @mtholder Shall we try `aenum` in peyotl and consider modifying its [requirements and setup files](https://github.com/OpenTreeOfLife/peyotl/search?q=enum34&type=code)?

**Comment by mtholder** [comment]
hmmm. Frustrating. In particular because `enum` is in the standard library in python 3, so we won't need this for long.

It looks like https://pypi.org/project/enum/#description might be the most lightweight replacement as it bills itself as a way to make code more robust. But I suspect that `aenum` would be fine too.

**Comment by jimallman** [comment]
I've tested a simpler solution that seems to work, installing enum34==1.1.10 for older python and skipping it for newer:
```
'enum34==1.1.10; python_version < "3.4"'
```
This change is in both `requirements.txt` and `setup.py`:
244e7a277a1812ca359b4aa1b779dd114871f9d3
86fb4ae140bdd6e9232996145e11c273986a47d9
